{{- if and .Values.configMap .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "universal-chart.fullname" . }}-config
  labels:
    {{- include "universal-chart.labels" . | nindent 4 }}
data:
  {{- if .Values.configMap.data }}
{{ toYaml .Values.configMap.data | indent 2 }}
  {{- else }}
  config.json: |
    {
      "domain": {{ and .Values.appConfig .Values.appConfig.domain | quote }},
      "env": {{ .Values.environment | default "dev" | quote }}
      {{- if and .Values.appConfig .Values.appConfig.googleWebClientId }},
      "google": {
        "webClientId": {{ .Values.appConfig.googleWebClientId | quote }}
      }
      {{- end }}
    }
  {{- end }}
{{- end }}
