{{- if .Values.vault.csi.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "universal-chart.fullname" . }}-vault-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault.svc:8200"
    role: {{ .Values.vault.role | default (printf "am-%s-role" (include "universal-chart.fullname" .)) | quote }}
    # Vault Kubernetes Authentication Path
    vaultCACertGen: "false"
    # Mapping secrets from Vault paths
    objects: |
      {{- range $k, $v := .Values.vault.secretPaths }}
      - objectName: "{{ $k }}"
        secretPath: "{{ if kindIs "string" $v }}{{ $v }}{{ else }}{{ $v.path }}{{ end }}"
        secretArgs:
          {{- range $moduleVar, $vaultKey := $v.mappings }}
          - key: "{{ $vaultKey }}"
          {{- end }}
      {{- end }}
  
  # OPTIONAL: Syncs CSI secrets to a native K8s Secret so the app can load them as Env Vars
  secretObjects:
    - secretName: {{ include "universal-chart.fullname" . }}-synced-secrets
      type: Opaque
      data:
        {{- range $k, $v := .Values.vault.secretPaths }}
        {{- range $moduleVar, $vaultKey := $v.mappings }}
        - objectName: "{{ $k }}"
          key: "{{ $vaultKey }}"
        {{- end }}
        {{- end }}
{{- end }}
