apiVersion: v1
kind: Service
metadata:
  name: {{ include "universal-chart.fullname" . }}
  labels:
    {{- include "universal-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "universal-chart.selectorLabels" . | nindent 4 }}
