{{- $vaultEnabled := or .Values.global.vault.enabled .Values.vault.enabled -}}
{{- if $vaultEnabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "universal-chart.fullname" . }}-vault-sa
  labels:
    {{- include "universal-chart.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
