{{- $vaultEnabled := or .Values.global.vault.enabled .Values.vault.enabled -}}
{{- $existingSA := .Values.global.vault.serviceAccountName | default "" -}}
{{- if and $vaultEnabled (not $existingSA) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "universal-chart.fullname" . }}-vault-sa
  labels:
    {{- include "universal-chart.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
{{- end }}
