global:
  image:
    registry: ghcr.io/AM-Portfolio
    tag: latest
    pullPolicy: IfNotPresent
  vault:
    enabled: false
    role: default-role
    authPath: auth/kubernetes
    secrets: {}

environment: default
replicaCount: 1

language: python

image:
  repository: ""

port: 8080

resources: {}
env: {}
